site_name: ContentGiver
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  logo: contentgiver.png
  favicon: contentgiver.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - search.suggest
    - header.autohide
    - navigation.indexes 
  icon:
    repo: fontawesome/brands/github 

repo_url: https://github.com/contentgiver
repo_name: ContentGiver